## "AlignmentSpace" -> "AlignmentSpace"
## "Alignment" -> "Alignment"
## "AnnotatedList" -> "SimpleList" or "CompressedList"
## "LogicalList" -> "SimpleLogicalList" or "CompressedLogicalList"
## "IntegerList" -> "SimpleIntegerList" or "CompressedIntegerList"
## "NumericList" -> "SimpleNumericList" or "CompressedNumericList"
## "ComplexList" -> "SimpleComplexList" or "CompressedComplexList"
## "CharacterList" -> "SimpleCharacterList" or "CompressedCharacterList"
## "RawList" -> "SimpleRawList" or "CompressedRawList"
## "RleList" -> "SimpleRleList" or "CompressedRleList"
## "FilterRules" -> "FilterRules"
## "IRanges" -> "IRanges"
## "NormalIRanges" -> "NormalIRanges"
## "IntervalTree" -> "IntervalTree"
## "MaskCollection" -> "MaskCollection"
## "RDApplyParams" -> "RDApplyParams"
## "RangedData" -> "RangedData"
## "RangedDataList" -> "RangedDataList"
## "RangesList" -> "SimpleRangesList"
## "IRangesList" -> "SimpleIRangesList" or "CompressedIRangesList"
## "RangesMatchingList" -> "RangesMatchingList"
## "Rle" -> "Rle"
## "RleViews" -> "RleViews"
## "XDataFrame" -> "DataFrame"
## "XDataFrameList" -> "SimpleDataFrameList"
## "SplitXDataFrameList" -> "SimpleSplitDataFrameList" or "CompressedSplitDataFrameList"
## "XInteger" -> "XInteger"
## "XIntegerViews" -> "XIntegerViews"
## "XNumeric" -> "XNumeric"
## "XRaw" -> "XRaw"
